apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-lqya
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0005-tenant/tkrw-pr712-0075-0005-app/devfile-sample-lqya@sha256:c6fcf51d94688e7579ee930538c89c9dc0ca2186518e23cda42df6ddd49b74ec
        name: my-nodejs
        resources: {}
status: {}
